##Dictionaries in Python Worksheet 6.1

Question - 1 : Write a python  program to given below are the two lists convert it into the dictionary . 

keys = ['Ten', 'Twenty', 'Thirty']

values = [10, 20, 30]

In [ ]:
#write your code here

In [1]:
keys=['Ten','Twenty','Thirty']
values=[10,20,30]
d=dict(zip(keys,values))

In [2]:
d

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

Question - 2 : Write a python program to delete set of keys from Python Dictionary

MyDict = {
  "name": "Rajit",
  "age":20,
  "salary": 8000000000,
  "city": "Agra" 
}

keysToRemove = ["name", "salary"]

output:

{ 'age': 20 , 'city': 'Agra'}

In [3]:
#write your code here
MyDict = {
  "name": "Rajit",
  "age":20,
  "salary": 8000000000,
  "city": "Agra" 
}
MyDict

{'name': 'Rajit', 'age': 20, 'salary': 8000000000, 'city': 'Agra'}

In [7]:

del MyDict["salary"]
MyDict

{'age': 20, 'city': 'Agra'}

In [14]:
MyDict={"name":"Rajit","age":20,"salary":80000000000,"city":"Agra"}

In [15]:
del MyDict["name"]
del MyDict["salary"]

In [16]:
MyDict

{'age': 20, 'city': 'Agra'}

Question - 3 : Write a python program to concatenate following dictionaries to create a new one. 

Dictionary :

dic1={1:10, 2:20}

dic2={3:30, 4:40}

dic3={5:50,6:60}

Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

In [8]:
#write your code here
dic1={1:10, 2:20}

dic2={3:30, 4:40}

dic3={5:50,6:60}

In [9]:
dic1.update(dic2)
dic1.update(dic3)

In [10]:
dic1

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

Question - 4 : Write a python program to check if a value 200 exists in a dictionary.

Dict = {'a': 100, 'b': 200, 'c': 300}

In [12]:
#write your code here
Dict = {'a': 100, 'b': 200, 'c': 300}
if 200 in Dict.values():
    print("exists")

exists

Question - 5 : Write a python program to rename key <b>city</b> to <b>location</b> in the following dictionary.

MyDict = {
  "name": "Rajit",
  "age":21,
  "salary": 8000000000,
  "city": "Agra"
  
}

In [13]:
#write your code here 
MyDict = {
  "name": "Rajit",
  "age":21,
  "salary": 8000000000,
  "city": "Agra"
  
}
print(MyDict)

{'name': 'Rajit', 'age': 21, 'salary': 8000000000, 'city': 'Agra'}

In [14]:
del MyDict["city"]
print(MyDict)

{'name': 'Rajit', 'age': 21, 'salary': 8000000000}

In [15]:
MyDict["location"] = "Agra"
print(MyDict)

{'name': 'Rajit', 'age': 21, 'salary': 8000000000, 'location': 'Agra'}

Question - 6 : Write a python program to get the key corresponding to the minimum value from the following dictionary.

sampleDict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}


output:
Math

In [18]:
#write your code here
sample = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}
min_key = min(sample,key=sample.get)
print(min_key)

Math

Question - 7 : Write a python program to given a Python dictionary, Change Shivaâ€™s salary to 8500

Dict1 = {

     'emp1': {'name': 'Ram', 'salary': 7500},

     'emp2': {'name': 'Shyam', 'salary': 8000},

     'emp3': {'name': 'Shiva', 'salary': 6500}

}

output:

Dict1 = {
  
     'emp1': {'name': 'Ram', 'salary': 7500},
     'emp2': {'name': 'Shyam', 'salary': 8000},
     'emp3': {'name': 'Shiva', 'salary': 8500}

}

In [20]:
#write your code here

Dict1 = {

     'emp1': {'name': 'Ram', 'salary': 7500},

     'emp2': {'name': 'Shyam', 'salary': 8000},

     'emp3': {'name': 'Shiva', 'salary': 6500}

}

In [22]:
Dict1['emp3']['salary'] = 8500
print(Dict1)

{'emp1': {'name': 'Ram', 'salary': 7500}, 'emp2': {'name': 'Shyam', 'salary': 8000}, 'emp3': {'name': 'Shiva', 'salary': 8500}}



```
# This is formatted as code
```

Question - 8 : Write a python program to generate and print a dictionary that contains a number (between 1 and n) in the form (x, x*x).

Dictionary ( n = 5) :

Output : {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [24]:
#write your code here
n = 5 
result = {x : x*x for x in range(1 , n+1)}
print(result)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

Question - 9 : Write a python program Write a Python program to multiply all the items in a dictionary.

my_dict = {'data1':100,'data2':-54,'data3':247}


 Output:
-1333800

In [40]:
#write your code here
my_dict = {'data1':100,'data2':-54,'data3':247}
result = 1
for value in my_dict.values():
    result *= value
print(result)

-1333800

Question - 10 : Write a python program  to get the maximum and minimum value in a dictionary.

:

my_dict = {'x':500, 'y':5874, 'z': 560}

 Output:

Maximum Value:  5874                                                                                          
Minimum Value:  500

In [44]:
#write your code here
my_dict = {'x':500, 'y':5874, 'z': 560}
min_value = min(my_dict.values())
print("min : ",min_value)
max_value = max(my_dict.values())
print("max : ", max_value)

min :  500
max :  5874